name: Docs

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'include/**'
  pull_request:
    branches: [master]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'include/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
    - name: Requirements
      run: sudo apt install doxygen
        && sudo apt install python3
        && sudo apt install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap

    - name: Checkout
      uses: actions/checkout@v3.0.0


    - name: Build docs
      run: cd docs
        && make html
        && cd _build/html
        && touch .nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        folder: docs/_build/html