name: Tests

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Requirements
      run: sudo apt install clang cmake ninja-build git

    - name: Checkout
      uses: actions/checkout@v3.0.0

    - name: Build tests
      run: cmake -DCMAKE_BUILD_TYPE=Release -B build -S . -G Ninja
        && cd build
        && ninja tests
      
    - name: Run CTest
      run: cd build && ctest -C Release -T test --output-on-failure
